blank_issues_enabled: false
contact_links:
  - name: ğŸ“§ Discord Support
    url: https://discord.gg/EXx8pYg7fm
    about: Nháº­n há»— trá»£ trá»±c tiáº¿p tá»« cá»™ng Ä‘á»“ng Discord
  - name: ğŸ’¬ Discussion Board
    url: https://github.com/sang765/HakoMonetTheme/discussions
    about: Tháº£o luáº­n Ã½ tÆ°á»Ÿng vÃ  cÃ¢u há»i chung
  - name: ğŸ“š Documentation
    url: https://github.com/sang765/HakoMonetTheme/wiki
    about: Kiá»ƒm tra wiki Ä‘á»ƒ biáº¿t hÆ°á»›ng dáº«n chi tiáº¿t
